# These are supported funding model platforms

github: [ECONEURA]
patreon: econeura
open_collective: econeura-ia
ko_fi: econeura
tidelift: npm/econeura-ia
community_bridge: econeura-ia
liberapay: econeura
issuehunt: econeura
custom: ['https://www.econeura-ia.com/donate', 'https://www.paypal.me/econeura']
