version: "3.9"
services:
  workspace:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    volumes:
      - .:/workspaces/${COMPOSE_PROJECT_NAME:-econeura}
    command: sleep infinity
    depends_on:
      - db
      - redis
  db:
    image: postgres:16
    container_name: econeura_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ${DB_NAME:-econeura_dev}
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 20
  redis:
    image: redis:7
    container_name: econeura_redis
    ports: ["6379:6379"]
