name: Azure Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - staging
        - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'
      
      - name: Setup pnpm
        run: corepack enable && corepack prepare pnpm@9.12.2 --activate
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build applications
        run: pnpm build
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: econeura-${{ github.event.inputs.environment }}-web
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: apps/web/.next
      
      - name: Deploy API to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: econeura-${{ github.event.inputs.environment }}-api
          publish-profile: ${{ secrets.AZURE_API_PUBLISH_PROFILE }}
          package: apps/api/dist
