---
name: Retry
description: Ejecuta un comando con reintentos
inputs:
  command:
    description: Comando a ejecutar
    required: true
  max_attempts:
    description: Número máximo de intentos
    required: false
    default: '3'
  backoff_seconds:
    description: Espera entre intentos (segundos)
    required: false
    default: '10'
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        attempts=0
        max=${{ inputs.max_attempts }}
        backoff=${{ inputs.backoff_seconds }}
        while true; do
          attempts=$((attempts+1))
          echo "Attempt ${attempts}/${max}: ${{ inputs.command }}"
          if bash -lc "${{ inputs.command }}"; then
            echo "Command succeeded."
            break
          fi
          if [ "$attempts" -ge "$max" ]; then
            echo "Command failed after ${max} attempts."
            exit 1
          fi
          echo "Retrying in ${backoff}s…"
          sleep "${backoff}"
        done
