name: setup-node-pnpm
description: Set up Node 20 + pnpm 8 (correct order)
runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: "pnpm"
    - name: Enable Corepack & pin pnpm
      shell: bash
      run: |
        set -euo pipefail
        corepack enable
        corepack prepare pnpm@8.15.6 --activate
