#!/usr/bin/env bash
set -euo pipefail
mkdir -p artifacts
echo "Installing dependencies with pnpm (via corepack)..."
corepack enable || true
corepack prepare pnpm@8.7.0 --activate || true

if command -v pnpm >/dev/null 2>&1; then
  pnpm install --frozen-lockfile || pnpm install || true
  echo "Running pnpm audit (json)..."
  pnpm audit --json > artifacts/pnpm-audit.json || true
else
  echo "pnpm not available in runner; writing placeholder audit output"
  echo '{"error":"pnpm not available"}' > artifacts/pnpm-audit.json
fi

# Generate a simple score.json based on audit presence
VULN_COUNT=0
if [ -f artifacts/pnpm-audit.json ]; then
  VULN_COUNT=$(jq '.advisories | length // 0' artifacts/pnpm-audit.json 2>/dev/null || echo 0)
fi
cat > artifacts/score.json <<JSON
{
  "date": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "vulnerabilities": ${VULN_COUNT},
  "notes": "Placeholder score generated by scripts/ci_generate_score.sh"
}
JSON

echo "Artifacts written to artifacts/ (pnpm-audit.json, score.json)"
