name: ECONEURA HMAC Approval Gate
on: [pull_request]
jobs:
  security_gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate audit artifacts presence
        run: |
          if [ ! -d audit ]; then echo "Missing audit artifacts" >&2; exit 1; fi
      - name: Check HMAC approval artifact
        run: |
          if [ ! -f audit/approval_artifact.json ]; then echo "Approval artifact missing - manual sign required" >&2; exit 1; fi
