name: Approval Gate (HMAC)
on: [pull_request]
jobs:
  validate_approval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check approval artifact
        run: |
          if [ ! -f audit/approval_request_*.json ]; then echo "No approval_request found" >&2; exit 1; fi
          # CI must fetch key from Vault (set VAULT_ADDR & VAULT_TOKEN in GitHub Secrets) and run validation script
          echo "Approval artifact present. Manual validation required."
