name: Approval Gate (HMAC)
on: [pull_request]
permissions:
  contents: read
  pull-requests: read
jobs:
  validate_approval:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Check approval artifact
        run: |
          echo "=== HMAC Approval Validation ==="

          # Check for approval request files
          APPROVAL_FILES=$(find audit -name "approval_request_*.json" 2>/dev/null | wc -l)
          if [ "$APPROVAL_FILES" -eq 0 ]; then
            echo "::error::No approval_request_*.json files found in audit/ directory"
            exit 1
          fi

          echo "Found $APPROVAL_FILES approval request file(s)"

          # Check for signed approval
          if [ ! -f "audit/approval_signed.json" ]; then
            echo "::error::Missing audit/approval_signed.json - approval not signed"
            exit 1
          fi

          echo "Signed approval file found"

      - name: Validate HMAC signature
        run: |
          echo "=== Validating HMAC Signature ==="

          if [ ! -f "scripts/vault/validate_hmac_approval.sh" ]; then
            echo "::error::HMAC validation script not found"
            exit 1
          fi

          chmod +x scripts/vault/validate_hmac_approval.sh

          if ! ./scripts/vault/validate_hmac_approval.sh audit/approval_signed.json; then
            echo "::error::HMAC validation failed"
            exit 1
          fi

          echo "HMAC validation successful"

      - name: Verify approval metadata
        run: |
          echo "=== Verifying Approval Metadata ==="

          # Check if approval contains required fields
          if ! jq -e '.timestamp and .approved_by and .approval_type' audit/approval_signed.json >/dev/null 2>&1; then
            echo "::error::Approval file missing required metadata fields"
            exit 1
          fi

          echo "Approval metadata verified"
          echo "::notice::HMAC approval validation completed successfully"
