name: Basic Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4

    - name: Project Structure Validation
      run: |
        echo "=== Project Structure Validation ==="
        echo "Repository: ECONEURA-IA"

        # Check for required files
        REQUIRED_FILES=("package.json" "pnpm-lock.yaml" "README.md")
        for file in "${REQUIRED_FILES[@]}"; do
          if [ ! -f "$file" ]; then
            echo "::error::Required file missing: $file"
            exit 1
          fi
          echo "✓ $file found"
        done

        # Check for apps directory
        if [ ! -d "apps" ]; then
          echo "::error::Required directory missing: apps/"
          exit 1
        fi
        echo "✓ apps/ directory found"

        # Check for packages directory
        if [ ! -d "packages" ]; then
          echo "::error::Required directory missing: packages/"
          exit 1
        fi
        echo "✓ packages/ directory found"

        echo "Project structure: VALID"

    - name: Dependency Validation
      run: |
        echo "=== Dependency Validation ==="

        if [ -f "package.json" ]; then
          echo "✓ Node.js project detected"

          if [ -f "pnpm-lock.yaml" ]; then
            echo "✓ PNPM lockfile found"
          else
            echo "::warning::PNPM lockfile missing"
          fi
        fi

        if [ -f "pyproject.toml" ] || [ -f "requirements.txt" ] || [ -d "venv" ]; then
          echo "✓ Python components detected"
        fi

        echo "Dependencies: OK"

    - name: Configuration Files Check
      run: |
        echo "=== Configuration Files Check ==="

        CONFIG_FILES=(".gitignore" "tsconfig.base.json" "docker-compose.dev.yml")
        for file in "${CONFIG_FILES[@]}"; do
          if [ -f "$file" ]; then
            echo "✓ $file found"
          else
            echo "::warning::Configuration file missing: $file"
          fi
        done

        echo "Configuration check: COMPLETED"

    - name: Final Status
      run: |
        echo "=== Validation Summary ==="
        echo "✅ Basic validation completed successfully"
        echo "Repository structure: VALID"
        echo "Dependencies: OK"
        echo "::notice::All basic validations passed"