name: CI Base

on:
  push:
    branches: [ main, develop, 'pr/**' ]
  pull_request:
    branches: [ main, develop ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '20.17.0'
  PNPM_VERSION: '8.15.6'
  DEPLOY_ENABLED: false

permissions:
  contents: read

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Setup pnpm via Corepack
        run: |
          corepack enable
          corepack prepare pnpm@${{ env.PNPM_VERSION }} --activate
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Run linting
        run: pnpm lint
        
      - name: Type checking
        run: pnpm typecheck

  agents-gate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Check DEPLOY_ENABLED
        run: |
          if [ "${{ env.DEPLOY_ENABLED }}" = "true" ]; then
            echo "❌ DEPLOY_ENABLED está activado en branch no autorizado"
            exit 1
          fi
          echo "✅ DEPLOY_ENABLED correcto: ${{ env.DEPLOY_ENABLED }}"
          
      - name: Validate agents registry
        run: |
          if [ -f "configs/agents/registry.json" ]; then
            node -e "const fs=require('fs');const j=JSON.parse(fs.readFileSync('configs/agents/registry.json','utf8'));if(j.length<60){process.stderr.write('Need >=60 agents, have '+j.length);process.exit(1)}"
            echo "✅ Agents registry validation passed"
          else
            echo "⚠️ Agents registry not found, skipping validation"
          fi
