name: e2e-playwright
on: [push, pull_request]
env: { DEPLOY_ENABLED: 'false', BASE_URL: 'http://127.0.0.1:3000' }
permissions: { contents: read }
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node 20 + pnpm
        uses: actions/setup-node@v4
        with: { node-version: '20.17.0', cache: 'pnpm' }
      - run: corepack enable && corepack prepare pnpm@8.15.6 --activate
      - run: pnpm -w i
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Start Web (dev)
        run: pnpm --filter @econeura/web dev &
      - name: Wait Web health
        run: for i in {1..90}; do curl -fsS http://127.0.0.1:3000/health && exit 0; sleep 2; done; exit 1
      - name: Detect baseline
        id: base
        run: test -d apps/web/tests/playwright/__snapshots__ && echo "has=1" >> $GITHUB_OUTPUT || echo "has=0" >> $GITHUB_OUTPUT
      - name: Bootstrap snapshots
        if: steps.base.outputs.has == '0'
        run: pnpm --filter @econeura/web test:ui:update
      - name: Gate snapshots (≤2%)
        run: pnpm --filter @econeura/web test:ui
      - uses: actions/upload-artifact@v4
        if: always()
        with: { name: pw-report, path: apps/web/playwright-report }
name: e2e-playwright

on: [push, pull_request]

env: { DEPLOY_ENABLED: 'false', BASE_URL: 'http://127.0.0.1:3000' }
permissions: { contents: read }

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node 20 + pnpm
        uses: actions/setup-node@v4
        with: { node-version: '20.17.0', cache: 'pnpm' }
      - run: corepack enable && corepack prepare pnpm@8.15.6 --activate
      - run: pnpm -w i
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Start Web (dev)
        run: pnpm --filter @econeura/web dev &
      - name: Wait Web health
        run: for i in {1..90}; do curl -fsS http://127.0.0.1:3000/health && exit 0; sleep 2; done; exit 1
      - name: Detect baseline
        id: base
        run: test -d apps/web/tests/playwright/__snapshots__ && echo "has=1" >> $GITHUB_OUTPUT || echo "has=0" >> $GITHUB_OUTPUT
      - name: Bootstrap snapshots
        if: steps.base.outputs.has == '0'
        run: pnpm --filter @econeura/web test:ui:update
      - name: Gate snapshots (≤2%)
        run: pnpm --filter @econeura/web test:ui
      - uses: actions/upload-artifact@v4
        if: always()
        with: { name: pw-report, path: apps/web/playwright-report }
