name: Nightly Integrations Health

on:
  schedule:
    - cron: '0 3 * * *' # every day at 03:00 UTC
  workflow_dispatch: {}

jobs:
  health:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Build API
        run: pnpm --filter @econeura/api build
      - name: Start API (background)
        run: node apps/api/dist/index.js &
        env:
          PORT: 4000
          RATE_LIMIT_DISABLED: 'true'
      - name: Wait for API
        run: |
          for i in {1..20}; do
            nc -z 127.0.0.1 4000 && echo "API up" && break || sleep 1;
          done
      - name: Probe Make health endpoint
        run: node scripts/ci/check-integrations-health.mjs
        env:
          API_HOST: 127.0.0.1
          API_PORT: 4000
