name: K6 Smoke Tests

on:
  push:
    branches: [ main, develop, 'pr/**' ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEPLOY_ENABLED: false

permissions:
  contents: read
  pull-requests: write

jobs:
  k6-smoke-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Check deployment status
        id: deployment
        run: |
          if [ "${{ env.DEPLOY_ENABLED }}" = "true" ]; then
            echo "enabled=true" >> $GITHUB_OUTPUT
            echo "🚀 Deployment enabled - running k6 smoke tests"
          else
            echo "enabled=false" >> $GITHUB_OUTPUT
            echo "ℹ️ DEPLOY_ENABLED=false - skipping k6 smoke tests"
          fi
          
      - name: Setup k6
        if: steps.deployment.outputs.enabled == 'true'
        uses: grafana/setup-k6-action@v1
        
      - name: Check secrets availability
        if: steps.deployment.outputs.enabled == 'true'
        id: secrets
        run: |
          if [ -z "${{ secrets.K6_BASE_URL }}" ]; then
            echo "available=false" >> $GITHUB_OUTPUT
            echo "⚠️ K6_BASE_URL secret not available"
          else
            echo "available=true" >> $GITHUB_OUTPUT
            echo "✅ K6_BASE_URL secret available"
          fi
          
      - name: Run k6 smoke tests
        if: steps.deployment.outputs.enabled == 'true' && steps.secrets.outputs.available == 'true'
        env:
          K6_BASE_URL: ${{ secrets.K6_BASE_URL }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        run: |
          export BASE_URL="$K6_BASE_URL"
          echo "🧪 Running k6 smoke tests against: $BASE_URL"
          k6 run tests/perf/e2e.js
          
      - name: Skip notification
        if: steps.deployment.outputs.enabled == 'false'
        run: |
          echo "✅ K6 smoke tests skipped - DEPLOY_ENABLED=false"
          echo "This is expected for CI-only branches"
          
      - name: Teams alert on failure
        if: failure() && steps.deployment.outputs.enabled == 'true'
        run: |
          echo "❌ K6 smoke tests failed"
          echo "Performance gate (p95<2s) not met"
