name: k6-smoke
on:
  push:
    branches: ['**']
  workflow_dispatch: {}

jobs:
  perf:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      K6_BASE_URL: ${{ secrets.K6_BASE_URL }}
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: grafana/setup-k6@v1
      - name: Preflight secret
        id: preflight
        shell: bash
        run: |
          if [ -z "$K6_BASE_URL" ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
            echo "K6_BASE_URL not set → skipping smoke"
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi
      - name: Run k6 smoke
        if: steps.preflight.outputs.skip != 'true'
        run: |
          export BASE_URL="$K6_BASE_URL"
          npx --yes k6@0.49.0 run tests/perf/e2e.js
      - name: Teams alert on FAIL
        if: failure()
        run: echo "k6 smoke FAIL" # ver docs/ALERTS.md
  close-pr-on-fail:
    if: failure() && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Cerrar PR por fallo de k6 (p95<2s)
        uses: peter-evans/close-pull@v3
        with:
          comment: |
            ❌ Gate de rendimiento (k6 p95<2s) ha fallado. Ajusta rendimiento y vuelve a abrir el PR.
      # marker: k6-smoke.yml
