name: k6-smoke
on:
  push:
    branches: ['**']
  workflow_dispatch: {}

jobs:
  perf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: grafana/setup-k6@v1
      - name: Preflight secret
        id: preflight
        shell: bash
        env:
          BASE_URL: ${{ secrets.K6_BASE_URL }}
        run: |
          if [ -z "$BASE_URL" ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
            echo "K6_BASE_URL not set → skipping smoke"
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi
      - name: Run k6 smoke
        if: steps.preflight.outputs.skip != 'true'
        env:
          BASE_URL: ${{ secrets.K6_BASE_URL }}
        run: |
          npx --yes k6@0.49.0 run tests/perf/e2e.js
      # marker: k6-smoke.yml
