name: openapi-check
on: [push, pull_request]
env: { DEPLOY_ENABLED: 'false' }
permissions: { contents: read }
jobs:
  check:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env: { POSTGRES_PASSWORD: ci, POSTGRES_USER: ci, POSTGRES_DB: econeura_ci }
        options: >-
          --health-cmd="pg_isready -U ci" --health-interval=10s --health-timeout=5s --health-retries=5
        ports: ['5432:5432']
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node 20 + pnpm
        uses: actions/setup-node@v4
        with: { node-version: '20.17.0', cache: 'pnpm' }
      - run: corepack enable && corepack prepare pnpm@8.15.6 --activate
      - run: pnpm -w i
      - name: Start API
        run: bash scripts/ci/api-up.sh
      - name: Snapshot OpenAPI
        run: node scripts/openapi/snapshot.mjs
      - name: Lint spec
        run: npx @stoplight/spectral lint apps/api/openapi/openapi.yaml
      - name: Diff spec vs runtime
        run: node scripts/openapi/diff.mjs
name: openapi-check

on: [push, pull_request]

env: { DEPLOY_ENABLED: 'false' }
permissions: { contents: read }

jobs:
  check:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env: { POSTGRES_PASSWORD: ci, POSTGRES_USER: ci, POSTGRES_DB: econeura_ci }
        options: >-
          --health-cmd="pg_isready -U ci" --health-interval=10s --health-timeout=5s --health-retries=5
        ports: ['5432:5432']
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node 20 + pnpm
        uses: actions/setup-node@v4
        with: { node-version: '20.17.0', cache: 'pnpm' }
      - run: corepack enable && corepack prepare pnpm@8.15.6 --activate
      - run: pnpm -w i
      - name: Start API
        run: bash scripts/ci/api-up.sh
      - name: Snapshot OpenAPI
        run: node scripts/openapi/snapshot.mjs
      - name: Lint spec
        run: npx @stoplight/spectral lint apps/api/openapi/openapi.yaml
      - name: Diff spec vs runtime
        run: node scripts/openapi/diff.mjs
