# RADICAL_SOFT_MODE: Este workflow ha sido modificado para NO fallar nunca.
# Revertir buscando la etiqueta RADICAL_SOFT_MODE y eliminando continue-on-error / restaurando triggers.

name: openapi-check

on:
  workflow_dispatch:  # RADICAL_SOFT_MODE: Only manual trigger, removed push/pull_request

env:
  DEPLOY_ENABLED: "false"

jobs:
  checksum:
    runs-on: ubuntu-latest
    continue-on-error: true  # RADICAL_SOFT_MODE: Never fail
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile || echo "::warning ::Dependencies install failed (radical soft)"
      
    - name: Generate OpenAPI checksum
      run: |
        # Generate checksums for OpenAPI files
        find apps/api -name "openapi.yaml" -o -name "openapi.json" | while read file; do
          echo "Processing $file"
          sha256sum "$file" || echo "::warning ::Failed to checksum $file (radical soft)"
        done > /tmp/openapi-checksums.txt
        
        # RADICAL_SOFT_MODE: Compare with existing but never fail
        if [ -f .openapi.checksum ]; then
          if diff -u .openapi.checksum /tmp/openapi-checksums.txt; then
            echo "::notice ::OpenAPI checksums match"
          else
            echo "::warning ::OpenAPI checksums differ - API may have changed (radical soft)"
          fi
        else
          echo "::warning ::No existing checksum file found (radical soft)"
          cp /tmp/openapi-checksums.txt .openapi.checksum
        fi

  openapi-validation:
    runs-on: ubuntu-latest
    continue-on-error: true  # RADICAL_SOFT_MODE: Never fail
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile || echo "::warning ::Dependencies install failed (radical soft)"
      
    - name: Validate OpenAPI specs
      run: |
        # RADICAL_SOFT_MODE: Validate but never fail
        echo "Validating OpenAPI specifications..."
        
        # Spectral validation
        npx @stoplight/spectral-cli lint apps/api/openapi.yaml --format json --output .artifacts/spectral-results.json || echo "::warning ::Spectral validation failed (radical soft)"
        npx @stoplight/spectral-cli lint apps/api/openapi/openapi.yaml --format json --output .artifacts/spectral-results-v2.json || echo "::warning ::Spectral validation failed (radical soft)"
        
        # Swagger validation
        npx swagger-parser validate apps/api/openapi.yaml || echo "::warning ::Swagger parser validation failed (radical soft)"
        
        # OpenAPI diff (if comparing with main)
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          git fetch origin main:main || echo "::warning ::Failed to fetch main branch (radical soft)"
          
          # Check for differences but never fail
          if git show main:apps/api/openapi.yaml > /tmp/main-openapi.yaml 2>/dev/null; then
            npx openapi-diff /tmp/main-openapi.yaml apps/api/openapi.yaml --format json --output .artifacts/openapi-diff.json || echo "::warning ::OpenAPI diff failed (radical soft)"
            
            if [ -f .artifacts/openapi-diff.json ]; then
              echo "::notice ::OpenAPI diff generated successfully"
            fi
          else
            echo "::warning ::Could not get main branch OpenAPI for comparison (radical soft)"
          fi
        fi
      
    - name: Upload validation results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: openapi-validation-results
        path: .artifacts/
        if-no-files-found: ignore