name: OpenAPI Check

on:
  push:
    branches: [ main, develop, 'pr/**' ]
  pull_request:
    branches: [ main, develop ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '20.17.0'
  PNPM_VERSION: '8.15.6'
  DEPLOY_ENABLED: false

permissions:
  contents: read

jobs:
  openapi-validation:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: econeura_test
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 5432:5432
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Setup pnpm via Corepack
        run: |
          corepack enable
          corepack prepare pnpm@${{ env.PNPM_VERSION }} --activate
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Start API for testing
        run: bash scripts/ci/api-up.sh
        
      - name: Generate OpenAPI snapshot
        run: node scripts/openapi/snapshot.mjs
        
      - name: Lint OpenAPI specification
        run: npx @stoplight/spectral lint apps/api/openapi/openapi.yaml
        
      - name: Compare spec vs runtime
        run: node scripts/openapi/diff.mjs
