name: PR Management

on:
  schedule:
    # Ejecutar gestión de PRs diariamente a las 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch:
    # Permitir ejecución manual
    inputs:
      mode:
        description: 'Modo de ejecución'
        required: false
        default: 'full'
        type: choice
        options:
          - full
          - merge-only
          - conflicts-only
          - report-only
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  pr-management:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Setup jq
        run: sudo apt-get install -y jq

      - name: Execute PR Management
        id: pr-management
        run: |
          chmod +x scripts/maintenance/manage-prs.sh
          ./scripts/maintenance/manage-prs.sh

      - name: Generate PR Report
        run: |
          echo "## 📊 PR Management Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📈 Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Total PRs analyzed:** $TOTAL_PRS" >> $GITHUB_STEP_SUMMARY
          echo "- **Mergeable PRs:** $MERGEABLE_PRS" >> $GITHUB_STEP_SUMMARY
          echo "- **PRs with conflicts:** $CONFLICTING_PRS" >> $GITHUB_STEP_SUMMARY
          echo "- **Remaining PRs:** $FINAL_PRS" >> $GITHUB_STEP_SUMMARY
          echo "- **Merged today:** $MERGED_TODAY" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          echo "### 📋 Current Open PRs" >> $GITHUB_STEP_SUMMARY
          if [ "$FINAL_PRS" -gt 0 ]; then
            gh pr list --state open --json number,title,author,mergeable | jq -r '.[] | "- **PR #\(.number)**: \(.title) by @\(.author.login) (\(.mergeable))"' >> $GITHUB_STEP_SUMMARY
          else
            echo "🎉 No open PRs remaining!" >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY

          echo "### 🔄 Automated Actions Taken" >> $GITHUB_STEP_SUMMARY
          if [ "$MERGED_TODAY" -gt 0 ]; then
            echo "- ✅ **$MERGED_TODAY PRs** merged automatically" >> $GITHUB_STEP_SUMMARY
          fi
          if [ "$CONFLICTING_PRS" -gt 0 ]; then
            echo "- ⚠️  **$CONFLICTING_PRS PRs** require manual conflict resolution" >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY

          echo "### 📝 Next Steps" >> $GITHUB_STEP_SUMMARY
          if [ "$MERGEABLE_PRS" -gt 0 ]; then
            echo "1. **Wait for CI checks** to pass on Dependabot PRs" >> $GITHUB_STEP_SUMMARY
            echo "2. **Re-run this workflow** to merge approved PRs" >> $GITHUB_STEP_SUMMARY
          fi
          if [ "$CONFLICTING_PRS" -gt 0 ]; then
            echo "3. **Resolve conflicts** in package.json/pnpm-lock.yaml manually" >> $GITHUB_STEP_SUMMARY
            echo "4. **Review and merge** resolved PRs" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Upload PR Management Logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: pr-management-logs
          path: |
            scripts/maintenance/pr-management-*.log
            scripts/maintenance/auto-merge-*.log
            scripts/maintenance/conflict-resolution-*.log

      - name: Notify on Conflicts
        if: env.CONFLICTING_PRS > 0
        run: |
          echo "⚠️  $CONFLICTING_PRS PRs have conflicts that need manual resolution"
          echo "Check the PR Management logs for details"