name: progress-nightly
on:
  schedule:
    - cron: '15 3 * * *'  # 03:15 UTC diario
  workflow_dispatch: {}
jobs:
  progress:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'pnpm' }
      - run: pnpm install --frozen-lockfile
      - run: pnpm progress
      - run: pnpm supervisor:check || true
      - name: Commit paneles de progreso
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            status/progress.json
            status/progress-badge.svg
            PROGRESS.md
            docs/PROGRESS_PANEL_v3.md
            docs/PROGRESS_PANEL_SUP_v3.md
          message: 'chore(progress): nightly progress + supervisor panel'
          default_author: github_actions