name: route-linter

on:
  pull_request:
    branches: ['**']
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CI: true
  DEPLOY_ENABLED: "false"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Enable Corepack & pin pnpm
        run: |
          set -euxo pipefail
          corepack enable
          corepack prepare pnpm@9.10.0 --activate
          pnpm -v && node -v && npm -v
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Typecheck & Lint
        run: pnpm typecheck && pnpm lint
      - name: Route linter (/v1-only)
        run: pnpm route:linter
      - name: Quality one-liner
        if: always()
        run: pnpm ci:gates
